### ISSUE TITLE
body-parser is slow

### ISSUE THREAD

**Issue by jkyberneees** [carlok/rest-coin-benchmark#3]
Hi @carlok, first of all, thanks for referencing restana in this performance compilation.

I noticed that you are using the `body-parser` middleware in:
https://github.com/carlok/rest-coin-benchmark/blob/2836cf8a9edb1ce9b891212adc9baf6bfce57901/server/node/restana/indexrestana.js#L2

This middleware is not optimised for performance, affecting express and restana results. Can I kindly suggest you to also include tests where GET endpoints are also tested? So we can exclude the impact of body parsing?

Many thanks!

**Comment by carlok** [comment]
Hi @jkyberneees, restana and express have been added thanks to a PR by @alessandro-battezzati so I could ask him to have a look at them both. As you might have noticed, each framework uses POST and a JSON payload because, although quite simple, the benchmark is designed for the classic "writing/creating" scenario, therefore, it uses POST. Anyhow, thanks for your message and we'll try to let you know ASAP.

**Comment by carlok** [comment]
Hi, we added a note on the README because it's the best tradeoff we can do at the moment (this project is not very active).

**Comment by jkyberneees** [comment]
Many thanks @carlok, appreciated.
